### ISSUE TITLE
errors in Spark CRD setup. 

### ISSUE THREAD

**Issue by yahavb** [aws-samples/eks-spark-benchmark#6]
https://github.com/aws-samples/eks-spark-benchmark/blob/master/benchmark/README.md#install-spark-operator indicates the following 
```
helm init --service-account tiller
Error: unknown command "init" for "helm"

```

and 

```
helm install incubator/sparkoperator --namespace spark-operator --set enableWebhook=true --set sparkJobNamespace=default --set operatorImageName=seedjeffwan/spark-operator --set operatorVersion=v2.4.5
Error: must either provide a name or specify --generate-name
```

both generate errors

**Comment by nithu0115** [comment]
Hi @yahavb, 

> https://github.com/aws-samples/eks-spark-benchmark/blob/master/benchmark/README.md#install-spark-operator indicates the following
> 
> ```
> helm init --service-account tiller
> Error: unknown command "init" for "helm"
> ```
> 
Tiller was removed in helm 3, and therefore helm init is no longer necessary. 
> and
> 
> ```
> helm install incubator/sparkoperator --namespace spark-operator --set enableWebhook=true --set sparkJobNamespace=default --set operatorImageName=seedjeffwan/spark-operator --set operatorVersion=v2.4.5
> Error: must either provide a name or specify --generate-name
> ```
> 
> both generate errors

Try adding `--generate-name` to generate the name (and omit the NAME parameter)
